#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = FALSE)
script <- sub("^--file=", "", args[grepl("^--file=", args)])
here <- dirname(normalizePath(script))
.libPaths(c(file.path(here, "r-library"), .libPaths()))
stopifnot(requireNamespace("qs", quietly = TRUE))
source <- file.path(here, "external", "individualobject_seuratmetadataframe.qs")
x <- qs::qread(source, use_alt_rep = FALSE)
writeLines(capture.output(str(x, max.level = 2)), file.path(here, "inputs", "kamath_qs_structure.txt"))
saveRDS(x, file.path(here, "inputs", "kamath_author_metadata.rds"), compress = "gzip")
stopifnot(is.list(x), length(x) == 18L, all(vapply(x, is.data.frame, logical(1))))
export <- lapply(seq_along(x), function(i) {
    z <- x[[i]]
    stopifnot(!anyDuplicated(rownames(z)), !"source_cell_id" %in% names(z))
    z[] <- lapply(z, function(v) if (is.factor(v)) as.character(v) else v)
    data.frame(source_list_index = i, source_cell_id = rownames(z), z, check.names = FALSE)
})
export <- as.data.frame(data.table::rbindlist(export, use.names = TRUE, fill = TRUE))
stopifnot(!anyDuplicated(export$source_cell_id))
con <- gzfile(file.path(here, "inputs", "kamath_author_metadata.csv.gz"), "wt")
write.csv(export, con, row.names = FALSE, na = "")
close(con)
stopifnot(identical(x, readRDS(file.path(here, "inputs", "kamath_author_metadata.rds"))))
cat("Decoded rows", nrow(export), "columns", ncol(export), "from", length(x), "donor frames\n")
print(names(export))
print(head(export, 3))
print(table(export$clusters, useNA = "ifany"))
cat("PASS: author qs decoded and base-R RDS copy checked\n")
